### ISSUE TITLE
May be performance issues when redefining lots of remote actors

### ISSUE THREAD

**Issue by wiljohnhong** [sjtu-marl/malib#1]
https://github.com/sjtu-marl/malib/blob/3982db1185591e6279f988a3ae446b5d86d982c5/malib/manager/rollout_worker_manager.py#L68-L77

It seems each definition of worker_cls will be pickled and exported through Redis.

Ref:
https://github.com/ray-project/ray/issues/6240

It would be better put the worker_cls definition out of the for loop:)

**Comment by KornbergFresnel** [comment]
@wiljohnhong fixed up.
