### ISSUE TITLE
demo bugs

### ISSUE THREAD

**Issue by AI-YULU** [sjtu-marl/malib#10]
The demo has a bug:
![image](https://user-images.githubusercontent.com/24793848/126616252-bbdc9084-2a6d-4d1f-8036-502c363151b8.png)
when i add the 'env_id', there is another bug:
![image](https://user-images.githubusercontent.com/24793848/126616333-2a17b1ea-f872-49a4-8719-127ae0021138.png)
![image](https://user-images.githubusercontent.com/24793848/126616564-c4bddae1-0b74-4631-8a68-7ad84eb85a36.png)

**Comment by KornbergFresnel** [comment]
Thanks for your report, we've fixed this inconsistency. More details can be found in #11
