### ISSUE TITLE
Quick Start Error

### ISSUE THREAD

**Issue by Ppaddington** [sjtu-marl/malib#13]
Traceback (most recent call last):
  File "demo.py", line 3, in <module>
    from malib.envs.poker import poker_aec_env as leduc_holdem
  File "/root/malib/malib/envs/__init__.py", line 4, in <module>
    from .poker import PokerEnv
  File "/root/malib/malib/envs/poker/__init__.py", line 1, in <module>
    from .poker_aec_env import env as PokerEnv
  File "/root/malib/malib/envs/poker/poker_aec_env.py", line 11, in <module>
    from open_spiel.python.rl_environment import Environment as OPEN_SPIEL_ENV, TimeStep
ModuleNotFoundError: No module named 'open_spiel'

demo.py:
"""PSRO with PPO for Leduc Holdem"""

from malib.envs.poker import poker_aec_env as leduc_holdem
from malib.runner import run
from malib.rollout import rollout_func

env = leduc_holdem.env(fixed_player=True)

run(
    agent_mapping_func=lambda agent_id: agent_id,
    env_description={
        "creator": leduc_holdem.env,
        "config": {"scenario_configs": {"fixed_player": True}, "env_id": "leduc_holdem"}
        "possible_agents": env.possible_agents,
    },
    training={
        "interface": {
            "type": "independent",
            "observation_spaces": env.observation_spaces,
            "action_spaces": env.action_spaces
        },
    },
    algorithms={
        "PSRO_PPO": {
            "name": "PPO",
            "custom_config": {
                "gamma": 1.0,
                "eps_min": 0,
                "eps_max": 1.0,
                "eps_decay": 100,
            },
        }
    },
    rollout={
        "type": "async",
        "stopper": "simple_rollout",
        "callback": rollout_func.sequential
    }
)

**Comment by zbzhu99** [comment]
You have to install `open_spiel` as a package dependency.

https://github.com/deepmind/open_spiel/blob/master/docs/install.md
