### ISSUE TITLE
A Minor Error in Quick Start Demo Code

### ISSUE THREAD

**Issue by hanmochen** [sjtu-marl/malib#20]
In README Quick Start part
```python
  env_description={
        "creator": leduc_holdem.env,
        "config": {"scenario_configs": {"fixed_player": True}, "env_id": "leduc_holdem"}
        "possible_agents": env.possible_agents,
    }
```
A missing `,` after `"config": {"scenario_configs": {"fixed_player": True}, "env_id": "leduc_holdem"}`

**Comment by hanmochen** [comment]
Also, in Line 8
`env = leduc_holdem.env(fixed_player=True)` should be `env = leduc_holdem.PokerEnv(fixed_player=True)`

**Comment by KornbergFresnel** [comment]
The repo has been refactored, thus I closed this issue.
