### ISSUE TITLE
Docker image link in the documentation doesn't work

### ISSUE THREAD

**Issue by Thedatababbler** [sjtu-marl/malib#21]
Hi, I have followed the installation guide on the documentation, and tried to run the quick start code, but I encountered several problems during installation. I noticed there is a link for a docker image for cross-platform use, however, when I tried to click that docker's link, it redirects me to the same document page. So, would you mind releasing the docker image in the next version too? Thank you.

**Comment by KornbergFresnel** [comment]
MALib has been activated again :) we'll include the latest guides for docker use these days.
