### ISSUE TITLE
SMARTS(Scalable Multi-Agent Reinforcement Learning Training School for Autonomous Driving)

### ISSUE THREAD

**Issue by Yuanzhuo-Liu** [sjtu-marl/malib#23]
Hi!
I learned on RLChina that MAlib supports SMARTS, but I couldn't find an example of using a SMARTS environment in this repo.

Thasnks!

**Comment by KornbergFresnel** [comment]
@Yuanzhuo-Liu hi, we are integrating the SMARTS in this PR: #24
