### ISSUE TITLE
For SMAC Qimx/MADDPG config

### ISSUE THREAD

**Issue by Weiyuhong-1998** [sjtu-marl/malib#34]
It's really a nice work and according to your paper, running Qmix/MADDPG is really fast. But we didn't find a config about Qmix/MADDPG algorithm, We don't know how to run your Qmix/MADDPG program，so can you give us a config for the Qmix/MADDPG algorithm? 
![WeChat Work Screenshot_20211227124527](https://user-images.githubusercontent.com/83390487/147437368-0b53bcb5-2f44-4693-b0d9-a57c1acfaa01.png)

**Comment by zhuerfei** [comment]
Have you solved this problem bro? I have some questions of this framework, shall we talk about this.

**Comment by KornbergFresnel** [comment]
The repo has been refactored, thus I closed this issue
