### ISSUE TITLE
How to run in cluster or cross multiply machines?

### ISSUE THREAD

**Issue by xuehui1991** [sjtu-marl/malib#36]
Dear MALib support,

My question as following:
1) Can MALib run in cluster or multiply machines? How to set the config?
2) When running in single machines, how to set the config about agent number?

Thank you.

**Comment by xuehui1991** [comment]
@KornbergFresnel

**Comment by KornbergFresnel** [comment]
Please follow the guides in section [Clustered deployment](https://malib.readthedocs.io/en/latest/deployment.html).
