### ISSUE TITLE
Run example error

### ISSUE THREAD

**Issue by nuaasgq** [sjtu-marl/malib#44]
Hi, when i run the run_gym.py, it reports the following error:

![image](https://user-images.githubusercontent.com/37932212/182390362-97c6465f-13ff-481f-a418-6987423aa86b.png)
![image](https://user-images.githubusercontent.com/37932212/182390503-6814cac6-c984-48e0-887d-6d91bb5f3be7.png)
could you give me some help?

**Comment by KornbergFresnel** [comment]
Seems there is an incompatible version of numba to python3.7. Please upgrade your py to 3.8 then have another try. @nuaasgq

**Comment by nuaasgq** [comment]
Thanks! I upgrade py to 3.7.13 and the problem has been solved.

**Comment by KornbergFresnel** [comment]
@nuaasgq the training pipeline of MALib has been reconstructed, please follow the changes in `master` branch.
